config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buildings do
    resources :apartments
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartments, dependent: :destroy
    accepts_nested_attributes_for :apartments,
                                   allow_destroy: true,
                                   reject_if: proc {|attributes| attributes['number'].blank?}


    def to_s
        name
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :boss, class_name: "Worker", optional: true
    has_many :subordinates, class_name: "Worker", foreign_key: "boss_id"
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
    def index
        @building = Building.find params[:building_id] 
        @apartments = @building.apartments
    end

    def new
        @building = Building.find params[:building_id]
        @apartment = Apartment.new
    end

    def create
        @building = Building.find params[:building_id]
        @apartment = Apartment.new(apartment_params)#Strong parameters, previene ataques de mass assignment
        @apartment.building = @building
        respond_to do |format|
          if @apartment.save
            format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'Apartment was successfully created.' }
          else
            format.html { render :new }
          end
        end
    end
    
    def show
        @building = Building.find params[:building_id]
        @apartment = Apartment.find(params[:id])    
    end

    def edit
        @building = Building.find params[:building_id]
        @apartment = Apartment.find params[:id]
    end

    def update
        @building = Building.find params[:building_id]
        @apartment = Apartment.find params[:id]
        respond_to do |format|
            if @apartment.update(apartment_params.merge(building: @building))# Se añade el building que se obtuvo en la llamada a find_building
            format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'Apartment was successfully updated.' }
            else
            format.html { render :edit }
            end
        end
    end

    def destroy
        @apartment = Apartment.find params[:id]
        @apartment.destroy
        respond_to do |format|
          format.html { redirect_to building_apartments_url, notice: 'Apartment was successfully destroyed.' }
        end
      end

    private
    def apartment_params
        params.require(:apartment).permit(:number)
    end

    def find_building
        @building = Building.find params[:building_id]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @buildings = Building.all
    
  end
    
  def new
    @building = Building.new
    @building.apartments.build
  end
  
  def create
    @building = Building.new(building_params)
    if @building.save
     redirect_to building_path(@building)
    else
     render ‘new’
    end
  end

  def show
    @building = Building.find params[:id]
  end

  def edit
    @building = Building.find params[:id]
  end

  def update
    @building = Building.find params[:id]
    respond_to do |format|
      if @building.update_attributes(building_params)
        format.html { redirect_to building_path(@building), notice: 'Building was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @building = Building.find params[:id]
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
    end
  end
  
  private
   def building_params
      # Esto permite que los atributos de apartment sean guardados.
      # El parametró destroy  nos permite eliminar un apartment cuando se enviar el formulario.
      params.require(:building).permit(:name, apartments_attributes: [:id, :number, :sale_price, :_destroy])
   end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: [@building, apartment], local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>
<%= render 'form', apartment: @apartment %>
<%= link_to 'Show', building_apartment_path(@building, @apartment) %> |
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.number %></td>
        <td><%= apartment.building %></td>
        <td><%= link_to 'Show', building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Edit', edit_building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Destroy', building_apartment_path(@building, apartment), method: :delete, data: {confirm: 'Are you sure?'}  %></td>
        <td><%= link_to 'New Apartment', new_building_apartment_path(@building, apartment)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Buildings', buildings_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @apartment.number %>
</p>

<p>
  <strong>Building:</strong>
  <%= @apartment.building.name %>
</p>


<%= link_to 'Edit', edit_building_apartment_path(@building, @apartment) %> |
<%= link_to 'Back', building_apartments_path(@building) %> 

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>Building fields</p>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <p>Apartment fields</p>
  
  <%= form.fields_for :apartments do |apartment_form| %>
    <%= apartment_form.label :number %>
    <%= apartment_form.text_field :number %>
    <%= apartment_form.label :sale_price %>
    <%= apartment_form.text_field :sale_price %>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.id %></td>
        <td><%= building.name %></td>
        <td><%= link_to 'Show', building_path(building) %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building_path(building), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path(@building) %> 

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path(@building) %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Building:</strong>
  <%= @building %>
</p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Sale Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @building.apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.number %></td>
        <td><%= apartment.sale_price %></td>
        <td><%= link_to 'Show', building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Edit', edit_building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Destroy', building_apartment_path(@building, apartment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdEdificio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>